#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys
import secrets
import numpy as np
import json


def PassGen(amount, count, special, name, is_file):

    js = open("alph.json","r")
    full_alph = json.load(js)
    
    simb = full_alph["alph"]
    s_simb = full_alph["s_alph"]

    if special == "True":
        us_alph = np.append(simb, s_simb)

    else:
        us_alph = simb

    lst = ""
    password = ""

    for i in range(count):
        password = ""
        for j in range(amount):
            password += secrets.choice(us_alph)
        lst += password + "\n"
    if is_file == "True":
        file = open(name+".txt", "w")
        file.write(lst)
    print()
    print(lst)


if __name__ == "__main__":
    amount_ = 8
    count_ = 10
    special_ = "True"
    name_ = "pass"
    file_ = "False"
    for i in range(len(sys.argv)):
        if sys.argv[i] == "-h" or sys.argv[i] == "--help" or len(sys.argv) == 0:
            print("""
-a or --amount  : number of characters in the password (int)
-c or --count   : amount passwords (int)
-s or --special : use or not use special characters (y 1 true True or other)
-n or --name    : output file name (str)
-f or --file    : create a text file or not (does not require parameters)
            """)
            sys.exit(0)
        if sys.argv[i] == "-a" or sys.argv[i] == "--amount":
            amount_ = int(sys.argv[i+1])

        if sys.argv[i] == "-c" or sys.argv[i] == "--count":
            count_ = int(sys.argv[i+1])

        if sys.argv[i] == "-s" or sys.argv[i] == "--special":
            special_ = sys.argv[i+1]

        if sys.argv[i] == "-n" or sys.argv[i] == "--name":
            name_ = sys.argv[i+1]
        if sys.argv[i] == "-f" or sys.argv[i] == "--file":
            file_ = "True"

    PassGen(amount = amount_, count = count_, special = special_, name = name_, is_file = file_)
